export default NavigationString = {
    HOME: "HOME",
    FAVORITES: 'FAVORITES',
    MYBLOGS: 'MY BLOGS',
    PROFILE: 'PROFILE',
    SETTINGS: "SETTINGS",
    BLOG: "BLOG",
    HOMESTACK: "HOME STACK",
    BLOGSTACK: "BLOG STACK",
    ADDBLOG: "ADD BLOG",
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    PROFILESTACK: "PROFILE STACK",
    CHANGEPASSWORD: "CHANGE PASSWORD",
    VERIFYEMAIL: "VERIFY EMAIL",
    FORGETPASSWORD: "FORGET PASSWORD",
    EDITOR: "EDITOR",
    SIGNOUT: 'SIGN OUT'
}