export const ThemeColors = {
    GRAY: "#333",
    PINK: "pink",
    WHITE: "#fff",
    BLACK: "#000",
    RED: '#F63B3B',
    GOLD: '#f5c608',
    BLUE: '#5191D8',
    TOMATO: 'tomato',
    INDIGO: "indigo",
    GREEN: "#89d6ce",
    PURPLE: "purple",
    ORANGE: "orange",
    CGREEN: "#12B28E",
    LIGHTGRAY: "lightgrey",
    CADETBLUE: "cadetblue",
    BLACKOPACITY80: "rgba(0,0,0,0.8)",
    BLACKOPACITY50: "rgba(0,0,0,0.5)",
    BLACKOPACITY_8: "rgba(0,0,0,0.08)",
}